### ISSUE TITLE
git-switch should be removed or renamed

### ISSUE THREAD

**Issue by Amorymeltzer** [unixorn/git-extra-commands#119]
Git 2.23 [added](https://github.com/git/git/blob/master/Documentation/RelNotes/2.23.0.txt) a `switch` command in core, so this should be either removed or renamed.  I'll note that the [upstream source](https://github.com/Andrew565/dotfiles) recently [tweaked](https://github.com/Andrew565/dotfiles/commit/704bacf568c7bca918eb401371eb3efe44b304ee) the function, and it seems like an improvement, so if it's kept that could be done as well.

**Comment by unixorn** [comment]
Thanks for the catch
