### ISSUE TITLE
Are both `branch-name` and `current-branch` needed?

### ISSUE THREAD

**Issue by Amorymeltzer** [unixorn/git-extra-commands#122]
The only difference is that [`git-branch-name`](https://github.com/unixorn/git-extra-commands/blob/6c39b775d65662abff78abfae6390c157fcd60ad/bin/git-branch-name) specifically eschews the whitespace while [`git-current-branch`](https://github.com/unixorn/git-extra-commands/blob/6c39b775d65662abff78abfae6390c157fcd60ad/bin/git-current-branch) doesn't, but, similar to https://github.com/unixorn/git-extra-commands/pull/115#issuecomment-628541420 and #121, are both needed?  I don't think there's a clear semantic difference.

**Comment by unixorn** [comment]
I was keeping them both to keep from breaking people's scripts. I'm going to replace `git-current-branch` with a symlink to `git-branch-name`.
