### ISSUE TITLE
Would you be willing to merge?

### ISSUE THREAD

**Issue by lordadamson** [unixorn/git-extra-commands#14]
I created [gitbaby](https://github.com/lordadamson/gitbaby) which stores locations to frequently used git repos in a file and using commands like `git cd` you can get into your repo. example: `git cd horse` and it changes working directory to wherever that project is.

The thing is, I modify the user's .bashrc and I store a file in ~/.gitbaby/git_repos to store the repos. so would you be willing to merge my git commands?

**Comment by unixorn** [comment]
Sorry it has taken so long to get back to you on this. I'll take a look at gitbaby and see how it can be integrated. At the very least, I can add a link to it in the external git utilities section.

**Comment by lordadamson** [comment]
thank you for looking into it :))

**Comment by lordadamson** [comment]
Thank you :D
