### ISSUE TITLE
No command completion with oh-my-zsh

### ISSUE THREAD

**Issue by tGrottker** [unixorn/git-extra-commands#62]
I set up a new oh-my-zsh, which is working fine. After following the installation instructions provided, all commands are available and work as expected, but the command completion does not.

This is my plugins definition:
`plugins=(command-not-found common-aliasses docker git git-extras git-extra-commands git-flow mvn sudo svn wd)`

**Comment by unixorn** [comment]
No one's written completion scripts for the tools in git-extra-commands. I keep meaning to, but haven't gotten around to it.
