### ISSUE TITLE
git-authors seems not working

### ISSUE THREAD

**Issue by izikeros** [unixorn/git-extra-commands#683]
When running git-authors, I'm getting an error:
```
fatal: ambiguous argument '': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

When omitting "WHERE" in `git log --pretty=format:'%an <%ae>' "$WHERE" | sort | uniq -c | sort -nr`, it works as expected.
```
git log --pretty=format:'%an <%ae>' | sort | uniq -c | sort -nr
```

**Comment by unixorn** [comment]
What OS are you using? I just checked it on my macOS box and an Ubuntu 22.04 box and it worked.

**Comment by izikeros** [comment]
Please close this Issue, there is no issue with $WHERE - I was using it wrong way. Sorry for the confusion.

**Comment by unixorn** [comment]
NP, glad it is working for you

**Comment by unixorn** [comment]
How should I update the documentation for it to be less confusing?
