### ISSUE TITLE
Add short description in README for each utility

### ISSUE THREAD

**Issue by phanimahesh** [unixorn/git-extra-commands#7]
Currently the only way to cherry pick scripts from here is to go through every script, read its header, and decide if I need it. Having a list of all scripts with description in README helps a lot.

The existing credits section can be renamed to Included Scripts, and both description and credit can be included right there.

**Comment by phanimahesh** [comment]
Thank you @unixorn! :)

**Comment by unixorn** [comment]
You're welcome!
